# Lec 3

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5], dtype = np.int)
print(a.shape)
print(a.ndim, a.dtype)

(5,)
1 int64


In [3]:
print(np.arange(5, 11))
print(np.linspace(0, 5, 11, dtype=np.float))
print(np.empty((2, 3), dtype=np.int))
print(np.zeros((2, 3)))
print(np.identity(4))
print(np.random.rand(3, 4))
print(np.random.random((2, 3)))

[ 5  6  7  8  9 10]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[[ 5  6  7]
 [ 8  9 10]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.58738248 0.34303368 0.8109994  0.89172415]
 [0.93813034 0.67365704 0.82849455 0.17175252]
 [0.44180552 0.26206965 0.82296958 0.40557865]]
[[0.62989093 0.23399885 0.4408145 ]
 [0.0872849  0.97078832 0.31970389]]


In [4]:
some_ints = np.array([[1,2], [3,4]], dtype=np.int64)
ident = np.identity(2, dtype=np.int32)
print(some_ints + ident)
print(some_ints * ident) # element-wise multiplication
print(some_ints @ ident) # matrix multiplication, or np.dot()
print(some_ints * 3)     # multiplication by a scalar

[[2 2]
 [3 5]]
[[1 0]
 [0 4]]
[[1 2]
 [3 4]]
[[ 3  6]
 [ 9 12]]


In [5]:
print(some_ints)
print(some_ints.sum())
print(some_ints.sum(axis=0))
print(some_ints.sum(axis=1))
print(np.sum(some_ints, axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]
[3 7]


In [6]:
def double_plus_single(x):
    return 2*x + 1

# double_plus_single = np.vectorize(double_plus_single, otypes=[np.float])
res = double_plus_single(some_ints)
print(res)
print(res.dtype)

[[3 5]
 [7 9]]
int64


In [7]:
def dot(x):
    return np.dot(x, x)

dot = np.vectorize(dot, otypes=[np.int])
res = dot(some_ints)
print(res)
print(np.dot(some_ints, some_ints))

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [8]:
a1a = np.zeros((3, 4))
print(a1a)
# a1b = np.zeros(2, 3) # error: must be a tuple

a2a = a1a.reshape((6, 2))
print(a2a)
a2b = a1a.reshape(6, 2)
print(a2b)
a2c = np.reshape(a1a, (6, 2))
print(a2c)
# a2d = np.reshape(a1a, 6, 2) # error: 2 is some other parameter

a3a = np.random.rand(2, 3)
print(a3a)
#a3b = np.random.rand((2, 3)) # error: can't be a tuple
a3c = np.random.random((2, 3))
print(a3c)
# a3d = np.random.random(2, 3) # error: must be a tuple

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.19529354 0.68308914 0.81697882]
 [0.34358369 0.46951555 0.48980384]]
[[0.57666901 0.99996955 0.30451517]
 [0.61940397 0.74419488 0.15092259]]


In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(
    {
        'value': [1, 2, 3, 4],
        'word': ['one', 'two', 'three', 'four']
    }
)
print(df)
df['double'] = df['value'] * 2
print(df)
print(df[df['value'] % 2 == 0])

   value   word
0      1    one
1      2    two
2      3  three
3      4   four
   value   word  double
0      1    one       2
1      2    two       4
2      3  three       6
3      4   four       8
   value  word  double
1      2   two       4
3      4  four       8


In [11]:
french_words = pd.Series(
    ['trois', 'deux', 'un'],
    index=[2, 1, 0]
)
df['french'] = french_words
print(df)

   value   word  double french
0      1    one       2     un
1      2    two       4   deux
2      3  three       6  trois
3      4   four       8    NaN


In [12]:
cities = pd.DataFrame(
  [[2463431, 2878.52], [1392609, 5110.21], [5928040, 5905.71]],
  columns=['population', 'area'],
  index=pd.Index(['Vancouver','Calgary','Toronto'], name='city')
)
print(cities)

           population     area
city                          
Vancouver     2463431  2878.52
Calgary       1392609  5110.21
Toronto       5928040  5905.71


In [13]:
def double_plus(x):
    return 2*x + 1
double_plus = np.vectorize(double_plus, otypes=[np.float])

cities['density'] = cities['population'] / cities['area']
cities['pop-rank'] = cities['population'].rank(ascending=False)
cities['something'] = double_plus(cities['population'])
print(cities)

           population     area      density  pop-rank   something
city                                                             
Vancouver     2463431  2878.52   855.797771       2.0   4926863.0
Calgary       1392609  5110.21   272.515024       3.0   2785219.0
Toronto       5928040  5905.71  1003.781086       1.0  11856081.0


In [14]:
del cities['something']
cities = cities.reset_index()
cities = cities.set_index('pop-rank')
cities.sort_values(by = 'pop-rank', inplace = True)
print(cities)

               city  population     area      density
pop-rank                                             
1.0         Toronto     5928040  5905.71  1003.781086
2.0       Vancouver     2463431  2878.52   855.797771
3.0         Calgary     1392609  5110.21   272.515024


# Lec 4

In [15]:
city_data = pd.read_csv('output.csv', index_col='rating')
city_data.sort_values(by = 'rating', inplace = True, ascending = False)
print(city_data)

                                     title
rating                                    
8.93                          Intouchables
8.67                          Garden State
8.60                     Dog Day Afternoon
8.50                        Mrs. Doubtfire
8.44                           Man on Fire
8.44                             El cuerpo
8.40                The Life of David Gale
8.33                    Dead Poets Society
8.20                            Real Steel
8.20                           Poltergeist
8.17                     War of the Worlds
8.14                            Detachment
8.12                     Dial M for Murder
8.00                                Vaiana
8.00                         Love Actually
8.00                  Jûsan-nin no shikaku
7.92                        A Time to Kill
7.83                        Wreck-It Ralph
7.59                         Me Before You
7.57                            Maleficent
7.55                Much Ado About Nothing
7.50       

In [34]:
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
          index=pd.Index(['row 1', 'row 2'], name = 'index'),
         columns=['col 1', 'col 2'])
df

col 1 col 2
index            
row 1     a     b
row 2     c     d

In [17]:
print(df.to_json(orient='records', lines=True))

{"col 1":"a","col 2":"b"}
{"col 1":"c","col 2":"d"}


In [35]:
cities = pd.DataFrame(
  [[2463431, 2878.52], [1392609, 5110.21], [5928040, 5905.71]],
  columns=['population', 'area'],
  index=pd.Index(['Vancouver','Vancouver','Toronto'], name='city')
)
print(cities)
result = cities.groupby(['city']).agg('sum').reset_index()
result

           population     area
city                          
Vancouver     2463431  2878.52
Vancouver     1392609  5110.21
Toronto       5928040  5905.71


city  population     area
0    Toronto     5928040  5905.71
1  Vancouver     3856040  7988.73

In [27]:
df = pd.DataFrame({'integer': [1, 2, 3, 4], 
                   'words': ['one', 'two', 'three', 'four'], 
                   'group': ['group1', 'group2', 'group1', 'group2']})
df.index.name = 'index'
df = df.groupby(['group', 'words']).agg('sum')
df

integer
group  words         
group1 one          1
       three        3
group2 four         4
       two          2